<!DOCTYPE html>
<html>
<body>
<b>Add Project<b><br>
<form method="post action="/project/addProject">
Project Name : <input type="text" name="projectName" placeholder="Enter project name"/><br>
Start Date : <input type="date" name="startDate" placeholder="Enter start date"/><br>
End Date : <input type="date" name="endDate" placeholder="Enter end date"/><br>
<input type="submit" value="Add Project"/>
</form>
<form>
<br>
<a href="/logout">Log out</a>
</form>
</body>
</html>